### ISSUE TITLE
朴素贝叶斯分类器的训练，有用到情感词典吗？

### ISSUE THREAD

**Issue by bandaren** [Robin-WZQ/Text-sentiment-polarity-judgment#1]

**Comment by Robin-WZQ** [comment]
您好！非常感谢您的提问！
朴素贝叶斯分类器中没有用到情感词典，我们这里希望通过单词在正负向情感文本中出现频率来表征情感程度。

**Comment by bandaren** [comment]
谢谢您的回复！还想请问您是否可以实现：用情感词典来训练朴素贝叶斯，得到的模型用来区分不同情感词的强度呢？这是一个常用的方式吗？谢谢！

**Comment by Robin-WZQ** [comment]
@bandaren 关于是否是常用方法因为我不是研究自然语言处理的，这个不能准确回答。此外，从直觉上讲，用情感词典训练Bayes是可以的，因为如2.4.3小节所述，TF-IDF、CHI就是一个基于统计的情感词典提取方式，所以拿手工定义的情感词典来做应该更好？
